servicetrack/pages/urls.py
__all__ = ()

import django.urls

import pages.views

app_name = "pages"

urlpatterns = [
    django.urls.path(
        "",
        pages.views.HomePageView.as_view(),
        name="home",
    ),
    django.urls.path(
        "about/",
        pages.views.AboutPageView.as_view(),
        name="about",
    ),
]

servicetrack/servicetrack/urls.py
__all__ = ()

import django.conf
import django.conf.urls.i18n
import django.conf.urls.static
import django.contrib
import django.contrib.admin
import django.urls

import company.urls
import pages.urls
import tickets.urls
import users.urls


urlpatterns = [
    django.urls.path("", django.urls.include(pages.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("auth/", django.urls.include(users.urls)),
    django.urls.path("company/", django.urls.include(company.urls)),
    django.urls.path("tickets/", django.urls.include(tickets.urls)),
    django.urls.path("i18n/", django.urls.include(django.conf.urls.i18n)),
]

if django.conf.settings.DEBUG:
    import debug_toolbar.toolbar

    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.STATIC_URL,
        document_root=django.conf.settings.STATIC_ROOT,
    )

    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

servicetrack/users/urls.py
__all__ = ()

import django.urls

from users import views

app_name = "users"

urlpatterns = [
    django.urls.path("login/", views.LoginView.as_view(), name="login"),
    django.urls.path("logout/", views.LogoutView.as_view(), name="logout"),
    django.urls.path(
        "register/",
        views.RegisterView.as_view(),
        name="register",
    ),
    django.urls.path(
        "password-change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    django.urls.path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    django.urls.path(
        "password-reset/",
        views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    django.urls.path(
        "password-reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    django.urls.path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    django.urls.path("profile/", views.ProfileView.as_view(), name="profile"),
    django.urls.path(
        "profile/edit/",
        views.ProfileUpdateView.as_view(),
        name="profile_edit",
    ),
    django.urls.path(
        "create/",
        views.UserCreateView.as_view(),
        name="user_create",
    ),
    django.urls.path(
        "user-list/",
        views.UserListView.as_view(),
        name="user_list",
    ),
]

servicetrack/users/forms.py
__all__ = ()

import django.contrib.auth.forms
import django.db.transaction
import django.forms
from django.utils.translation import gettext_lazy as _
import phonenumber_field.formfields

import company.models
import users.models


class CustomUserCreationForm(django.contrib.auth.forms.UserCreationForm):
    phone = phonenumber_field.formfields.PhoneNumberField(
        label=_("Телефон"),
        required=False,
        region="RU",
    )

    organization_name = django.forms.CharField(
        label=_("Название организации"),
        max_length=255,
        required=True,
    )

    class Meta(django.contrib.auth.forms.UserCreationForm.Meta):
        model = users.models.CustomUser
        fields = (
            users.models.CustomUser.username.field.name,
            users.models.CustomUser.email.field.name,
            users.models.CustomUser.first_name.field.name,
            users.models.CustomUser.last_name.field.name,
            users.models.Profile.phone.field.name,
            "organization_name",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = _("Имя_пользователя")
        self.fields["password1"].label = _("Пароль")
        self.fields["password2"].label = _("Подтверждение_пароля")

    def save(self, commit=True):
        with django.db.transaction.atomic():
            user = super().save(commit=False)
            user.save()

            if commit:
                organization = company.models.Organization.objects.create(
                    name=self.cleaned_data["organization_name"],
                    main_manager=user,
                )

                user.refresh_from_db()
                profile = user.profile

                profile.phone = self.cleaned_data.get("phone", None)
                profile.organization = organization
                profile.role = users.models.Profile.Role.MAIN_MANAGER
                profile.save()

            return user


class CustomAuthenticationForm(django.contrib.auth.forms.AuthenticationForm):
    username = django.forms.CharField(
        label=_("Имя_пользователя"),
        widget=django.forms.TextInput(attrs={"autofocus": True}),
    )
    password = django.forms.CharField(
        label=_("Пароль"),
        strip=False,
        widget=django.forms.PasswordInput(
            attrs={"autocomplete": "current-password"},
        ),
    )

    error_messages = {
        "invalid_login": _(
            "Пожалуйста,_введите_правильные имя_пользователя_и_пароль."
            "Оба_поля_могут_быть_чувствительны_к_регистру.",
        ),
        "inactive": _("Этот_аккаунт_неактивен"),
    }


class CustomPasswordChangeForm(django.contrib.auth.forms.PasswordChangeForm):
    old_password = django.forms.CharField(
        label=_("Старый_пароль"),
        strip=False,
        widget=django.forms.PasswordInput(
            attrs={"autocomplete": "current-password", "autofocus": True},
        ),
    )
    new_password1 = django.forms.CharField(
        label=_("Новый_пароль"),
        widget=django.forms.PasswordInput(
            attrs={"autocomplete": "new-password"},
        ),
        strip=False,
    )
    new_password2 = django.forms.CharField(
        label=_("Подтверждение_нового_пароля"),
        strip=False,
        widget=django.forms.PasswordInput(
            attrs={"autocomplete": "new-password"},
        ),
    )


class CustomPasswordResetForm(django.contrib.auth.forms.PasswordResetForm):
    email = django.forms.EmailField(
        label=_("Электронная_почта"),
        max_length=254,
        widget=django.forms.EmailInput(attrs={"autocomplete": "email"}),
    )


class CustomSetPasswordForm(django.contrib.auth.forms.SetPasswordForm):
    new_password1 = django.forms.CharField(
        label=_("Новый_пароль"),
        widget=django.forms.PasswordInput(
            attrs={"autocomplete": "new-password"},
        ),
        strip=False,
    )
    new_password2 = django.forms.CharField(
        label=_("Подтверждение_нового_пароля"),
        strip=False,
        widget=django.forms.PasswordInput(
            attrs={"autocomplete": "new-password"},
        ),
    )


class UserCreateForm(django.forms.ModelForm):
    password1 = django.forms.CharField(
        label=_("Пароль"),
        widget=django.forms.PasswordInput,
    )
    password2 = django.forms.CharField(
        label=_("Подтверждение пароля"),
        widget=django.forms.PasswordInput,
    )

    class Meta:
        model = users.models.CustomUser
        fields = (
            users.models.CustomUser.username.field.name,
            users.models.CustomUser.email.field.name,
            users.models.CustomUser.first_name.field.name,
            users.models.CustomUser.last_name.field.name,
        )

    def __init__(self, *args, **kwargs):
        self.creator = kwargs.pop("creator")
        super().__init__(*args, **kwargs)

        choices = [(users.models.Profile.Role.WORKER, _("Работник"))]

        if self.creator.profile.is_director:
            choices.append(
                (
                    users.models.Profile.Role.GROUP_MANAGER,
                    _("Руководитель_группы"),
                ),
            )

        self.fields["role"] = django.forms.ChoiceField(
            label=_("Роль"),
            choices=choices,
            required=True,
        )

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data.get("password1") != cleaned_data.get("password2"):
            raise django.forms.ValidationError(_("Пароли_не_совпадают"))

        return cleaned_data

    def save(self, commit=True):
        with django.db.transaction.atomic():
            creator = self.creator

            user = super().save(commit=False)
            user.set_password(self.cleaned_data["password1"])
            user.save()

            user.refresh_from_db()
            user.profile.organization_id = creator.profile.organization_id
            user.profile.role = self.cleaned_data["role"]
            user.profile.save()

            if creator.profile.is_manager:
                group = creator.managed_groups.first()
                if group:
                    group.workers.add(user)

            return user


class UserProfileUpdateForm(django.forms.ModelForm):
    phone = phonenumber_field.formfields.PhoneNumberField(
        label=_("Телефон"),
        required=False,
        region="RU",
    )

    class Meta:
        model = users.models.CustomUser
        fields = (
            users.models.CustomUser.username.field.name,
            users.models.CustomUser.email.field.name,
            users.models.CustomUser.first_name.field.name,
            users.models.CustomUser.last_name.field.name,
            users.models.Profile.phone.field.name,
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and hasattr(self.instance, "profile"):
            self.fields["phone"].initial = self.instance.profile.phone

    def save(self, commit=True):
        with django.db.transaction.atomic():
            user = super().save(commit=False)

            if commit:
                user.save()
                if hasattr(user, "profile"):
                    user.profile.phone = self.cleaned_data.get("phone")
                    user.profile.save()

            return user

servicetrack/users/views.py
__all__ = ()

import collections

import django.contrib
import django.contrib.auth.mixins
import django.contrib.auth.views
import django.db.models
import django.http
import django.urls
from django.utils.translation import gettext_lazy as _
import django.views.generic

import core.mixins
import users.forms
import users.models


class RegisterView(
    django.contrib.auth.mixins.UserPassesTestMixin,
    django.views.generic.CreateView,
):
    form_class = users.forms.CustomUserCreationForm
    template_name = "users/register.html"
    success_url = django.urls.reverse_lazy("users:login")

    def test_func(self):
        return not self.request.user.is_authenticated


class LoginView(django.contrib.auth.views.LoginView):
    form_class = users.forms.CustomAuthenticationForm
    template_name = "users/login.html"
    redirect_authenticated_user = True
    success_url = django.urls.reverse_lazy("users:profile")

    def get(self, request, *args, **kwargs):
        params = request.GET
        if "username" in params:
            user = users.models.CustomUser.objects.filter(
                username=params["username"],
            )
            if not user:
                return super().get(self, request, *args, **kwargs)

            django.contrib.auth.login(request, user[0])
            return django.http.HttpResponseRedirect(
                django.urls.reverse("users:user_list"),
            )

        return super().get(self, request, *args, **kwargs)


class LogoutView(django.contrib.auth.views.LogoutView):
    template_name = "users/logout.html"
    next_page = django.urls.reverse_lazy("users:login")


class PasswordChangeView(django.contrib.auth.views.PasswordChangeView):
    form_class = users.forms.CustomPasswordChangeForm
    template_name = "users/password_change.html"
    success_url = django.urls.reverse_lazy("users:password_change_done")


class PasswordChangeDoneView(django.contrib.auth.views.PasswordChangeDoneView):
    template_name = "users/password_change_done.html"


class PasswordResetView(django.contrib.auth.views.PasswordResetView):
    form_class = users.forms.CustomPasswordResetForm
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    subject_template_name = "users/password_reset_subject.txt"
    success_url = django.urls.reverse_lazy("users:password_reset_done")


class PasswordResetDoneView(django.contrib.auth.views.PasswordResetDoneView):
    template_name = "users/password_reset_done.html"


class PasswordResetConfirmView(
    django.contrib.auth.views.PasswordResetConfirmView,
):
    form_class = users.forms.CustomSetPasswordForm
    template_name = "users/password_reset_confirm.html"
    success_url = django.urls.reverse_lazy("users:password_reset_complete")


class PasswordResetCompleteView(
    django.contrib.auth.views.PasswordResetCompleteView,
):
    template_name = "users/password_reset_complete.html"


class ProfileView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.TemplateView,
):
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile
        return context


class UserCreateView(
    core.mixins.ForbiddenMixin,
    django.views.generic.CreateView,
):
    form_class = users.forms.UserCreateForm
    template_name = "users/user_create.html"
    success_url = django.urls.reverse_lazy("users:user_list")

    def test_func(self):
        user = self.request.user
        return user.profile.role in [
            users.models.Profile.Role.MAIN_MANAGER,
            users.models.Profile.Role.GROUP_MANAGER,
        ]

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["creator"] = self.request.user
        return kwargs

    def form_valid(self, form):
        django.contrib.messages.success(
            self.request,
            _("Пользователь_успешно_создан"),
        )
        return super().form_valid(form)


class UserListView(
    core.mixins.ForbiddenMixin,
    django.views.generic.ListView,
):
    model = users.models.CustomUser
    template_name = "users/user_list.html"
    context_object_name = "users"

    def test_func(self):
        user = self.request.user
        return user.profile.role in [
            users.models.Profile.Role.MAIN_MANAGER,
            users.models.Profile.Role.GROUP_MANAGER,
        ]

    def get_queryset(self):
        user = self.request.user

        queryset = (
            super()
            .get_queryset()
            .select_related("profile")
            .prefetch_related("work_groups")
            .filter(
                profile__organization_id=user.profile.organization_id,
            )
        )

        queryset = queryset.exclude(
            profile__role=users.models.Profile.Role.MAIN_MANAGER,
        )

        if user.profile.is_manager:
            queryset = queryset.filter(
                django.db.models.Q(work_groups__manager_id=user.id)
                | django.db.models.Q(work_groups__isnull=True),
            ).distinct()

        return queryset.exclude(id=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user

        grouped_dict = collections.defaultdict(list)
        for user in self.object_list:
            user_groups = user.work_groups.all()

            if user_groups:
                for group in user_groups:
                    if (
                        current_user.profile.is_director
                        or group.manager_id == current_user.id
                    ):
                        grouped_dict[group].append(user)
            else:
                grouped_dict["_no_group"].append(user)

        context["groups"] = [
            {
                "group": group,
                "users": user_list,
            }
            for group, user_list in grouped_dict.items()
        ]

        return context


class ProfileUpdateView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.UpdateView,
):
    form_class = users.forms.UserProfileUpdateForm
    template_name = "users/profile_edit.html"
    success_url = django.urls.reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        django.contrib.messages.success(
            self.request,
            _("Профиль_успешно_обновлен"),
        )
        return super().form_valid(form)

servicetrack/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Вход" %} - ServiceTrack{% endblock %}

{% block content %}
<div class="row justify-content-center fade-in">
    <div class="col-md-8 col-lg-6">
        <div class="content-container p-4 p-md-5">
            <h2 class="text-center mb-4">{% trans "Вход_в_систему" %}</h2>

            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}

                <div class="mb-3">
                    <label for="{{ form.username.id_for_label }}" class="form-label">
                        {% trans "Имя_пользователя" %}
                    </label>
                    <input type="text"
                           name="{{ form.username.name }}"
                           id="{{ form.username.id_for_label }}"
                           class="form-control form-control-lg {% if form.username.errors %}is-invalid{% endif %}"
                           value="{{ form.username.value|default:'' }}"
                           placeholder="{% trans 'Введите_имя_пользователя' %}"
                           required>
                    {% for error in form.username.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="mb-4">
                    <label for="{{ form.password.id_for_label }}" class="form-label">
                        {% trans "Пароль" %}
                    </label>
                    <input type="password"
                           name="{{ form.password.name }}"
                           id="{{ form.password.id_for_label }}"
                           class="form-control form-control-lg {% if form.password.errors %}is-invalid{% endif %}"
                           placeholder="{% trans 'Введите_пароль' %}"
                           required>
                    {% for error in form.password.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {% for error in form.non_field_errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}

                <div class="d-grid gap-2 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg">
                        {% trans "Войти" %}
                    </button>
                </div>

                <div class="text-center mt-4">
                    <a href="{% url 'users:password_reset' %}"
                       class="btn btn-outline-secondary btn-sm d-inline-flex align-items-center mb-2">
                        {% trans "Забыли_пароль?" %}
                    </a>
                    <div class="mt-3 pt-3 border-top">
                        <p class="mb-0 text-muted">{% trans "Нет_аккаунта?" %}</p>
                        <a href="{% url 'users:register' %}" class="btn btn-outline-primary mt-2">
                            {% trans "Зарегистрироваться" %}
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

servicetrack/templates/users/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Выход" %} — {{ block.super }}{% endblock %}

{% block content %}
<h2>{% trans "Выход_из_системы" %}</h2>

{% if user.is_authenticated %}
    <p>{% trans "Вы_уверены,_что_хотите_выйти?" %}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn">{% trans "Выйти" %}</button>
        <a href="{% url 'pages:home' %}" class="btn btn-secondary">{% trans "Отмена" %}</a>
    </form>
{% else %}
    <p>{% trans "Вы_уже_вышли_из_системы." %}</p>
    <div style="margin-top: 20px;">
        <a href="{% url 'users:login' %}" class="btn">{% trans "Войти_снова" %}</a>
    </div>
{% endif %}
{% endblock %}

servicetrack/templates/users/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Смена_пароля" %} - ServiceTrack{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
        <div class="content-container p-4 p-md-5">
            <h2 class="text-center mb-4">{% trans "Смена_пароля" %}</h2>

            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_old_password" class="form-label">
                        {% trans "Старый_пароль" %}
                    </label>
                    <input type="password"
                           name="{{ form.old_password.name }}"
                           id="id_old_password"
                           class="form-control {% if form.old_password.errors %}is-invalid{% endif %}"
                           placeholder="{% trans 'Введите_текущий_пароль' %}"
                           required>
                    {% for error in form.old_password.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="mb-3">
                    <label for="id_new_password1" class="form-label">
                        {% trans "Новый_пароль" %}
                    </label>
                    <input type="password"
                           name="{{ form.new_password1.name }}"
                           id="id_new_password1"
                           class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
                           placeholder="{% trans 'Введите_новый_пароль' %}"
                           required>
                    {% for error in form.new_password1.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                    {% if form.new_password1.help_text %}
                    <div class="form-text">{{ form.new_password1.help_text|safe }}</div>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_new_password2" class="form-label">
                        {% trans "Подтверждение_нового_пароля" %}
                    </label>
                    <input type="password"
                           name="{{ form.new_password2.name }}"
                           id="id_new_password2"
                           class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
                           placeholder="{% trans 'Повторите_новый_пароль' %}"
                           required>
                    {% for error in form.new_password2.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                {% if form.non_field_errors %}
                <div class="alert alert-danger mb-4">
                    {% for error in form.non_field_errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}

                <div class="d-grid gap-2 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg">
                        {% trans "Сменить_пароль" %}
                    </button>
                </div>

                <div class="text-center">
                    <a href="{% url 'users:profile' %}" class="btn btn-outline-secondary">
                        {% trans "Вернуться_в_профиль" %}
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

servicetrack/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Ввод_нового_пароля" %} — {{ block.super }}{% endblock %}

{% block content %}
<div class="row justify-content-center fade-in">
    <div class="col-md-8 col-lg-6">
        <div class="content-container p-4 p-md-5">
            <h2 class="text-center mb-4">{% trans "Ввод_нового_пароля" %}</h2>

            {% if validlink %}
                <p class="text-center mb-4">{% trans "Пожалуйста,_введите_новый_пароль_дважды." %}</p>

                <form method="post" class="needs-validation" novalidate>
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="id_new_password1" class="form-label">{% trans "Новый_пароль" %}</label>
                        <input type="password"
                               name="{{ form.new_password1.name }}"
                               id="id_new_password1"
                               class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
                               placeholder="{% trans 'Введите_новый_пароль' %}"
                               required>
                        {% for error in form.new_password1.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>

                    <div class="mb-4">
                        <label for="id_new_password2" class="form-label">{% trans "Подтверждение_нового_пароля" %}</label>
                        <input type="password"
                               name="{{ form.new_password2.name }}"
                               id="id_new_password2"
                               class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
                               placeholder="{% trans 'Повторите_новый_пароль' %}"
                               required>
                        {% for error in form.new_password2.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>

                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary btn-lg">{% trans "Изменить_пароль" %}</button>
                        <a href="{% url 'users:login' %}" class="btn btn-outline-secondary">{% trans "Отмена" %}</a>
                    </div>
                </form>
            {% else %}
                <div class="alert alert-danger" role="alert">
                    
                    {% trans "Ссылка_для_сброса_пароля_недействительна,_возможно,_потому_что_она_уже_была_использована._Пожалуйста,_запросите_сброс_пароля_снова." %}
                </div>

                <div class="d-grid gap-2">
                    <a href="{% url 'users:password_reset' %}" class="btn btn-primary">
                        {% trans "Запросить_сброс_пароля" %}
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

servicetrack/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Вы_получили_это_письмо,_потому_что_запросили_сброс_пароля_для_вашей_учётной_записи_на_сайте_{{ site_name }}.{% endblocktrans %}

{% trans "Пожалуйста,_перейдите_по_следующей_ссылке_и_создайте_новый_пароль:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% blocktrans %}Ваше_имя_пользователя:_{{ username }}{% endblocktrans %}

{% trans "Если_вы_не_запрашивали_сброс_пароля, просто_проигнорируйте_это_письмо." %}
{% endautoescape %}

servicetrack/templates/users/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Профиль" %} — {{ block.super }}{% endblock %}

{% block content %}
<div class="row justify-content-center fade-in">
    <div class="col-md-8 col-lg-6">
        <div class="content-container p-4 p-md-5">
            <h2 class="text-center mb-4">{% trans "Профиль_пользователя" %}</h2>

            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    <div class="mb-3">
                        <label class="form-label text-muted small mb-1">{% trans "Имя_пользователя" %}</label>
                        <p class="form-control-plaintext">{{ user.username }}</p>
                    </div>

                    <div class="mb-3">
                        <label class="form-label text-muted small mb-1">{% trans "Email" %}</label>
                        <p class="form-control-plaintext">{{ user.email }}</p>
                    </div>

                    {% translate "Не_указано" as not_specified %}
                    <div class="mb-3">
                        <label class="form-label text-muted small mb-1">{% trans "Имя" %}</label>
                        <p class="form-control-plaintext">
                            {{ user.first_name|default:not_specified }}
                        </p>
                    </div>

                    <div class="mb-3">
                        <label class="form-label text-muted small mb-1">{% trans "Фамилия" %}</label>
                        <p class="form-control-plaintext">
                            {{ user.last_name|default:not_specified }}
                        </p>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-muted small mb-1">{% trans "Роль" %}</label>
                        <p class="form-control-plaintext">{{ profile.get_role_display|capfirst }}</p>
                    </div>

                    <div class="mb-3">
                        <label class="form-label text-muted small mb-1">{% trans "Телефон" %}</label>
                        <p class="form-control-plaintext">{{ profile.phone.as_international|default:not_specified }}</p>
                    </div>

                    <div class="mb-3">
                        <label class="form-label text-muted small mb-1">{% trans "Дата_регистрации" %}</label>
                        <p class="form-control-plaintext">{{ user.date_joined|date:"d.m.Y H:i" }}</p>
                    </div>
                </div>
            </div>

            <div class="d-grid gap-2 mt-4">
                <a href="{% url 'users:profile_edit' %}" class="btn btn-primary">
                    {% trans "Редактировать_профиль" %}
                </a>
                <a href="{% url 'users:password_change' %}" class="btn btn-outline-primary">
                    {% trans "Сменить_пароль" %}
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}