servicetrack/company/urls.py
__all__ = ()

import django.urls

from company import views

app_name = "company"

urlpatterns = [
    django.urls.path(
        "organization-detail/<int:pk>/",
        views.OrganizationView.as_view(),
        name="organization_detail",
    ),
    django.urls.path(
        "organization-edit/<int:pk>/",
        views.OrganizationEditView.as_view(),
        name="organization_edit",
    ),
    django.urls.path(
        "group-detail/<int:pk>/",
        views.GroupDetailView.as_view(),
        name="group_detail",
    ),
    django.urls.path(
        "group-edit/<int:pk>/",
        views.GroupEditView.as_view(),
        name="group_edit",
    ),
    django.urls.path(
        "group-list/",
        views.GroupListView.as_view(),
        name="group_list",
    ),
    django.urls.path(
        "group-create/",
        views.GroupCreateView.as_view(),
        name="group_create",
    ),
]

servicetrack/pages/urls.py
__all__ = ()

import django.urls

import pages.views

app_name = "pages"

urlpatterns = [
    django.urls.path(
        "",
        pages.views.HomePageView.as_view(),
        name="home",
    ),
    django.urls.path(
        "about/",
        pages.views.AboutPageView.as_view(),
        name="about",
    ),
]

servicetrack/servicetrack/urls.py
__all__ = ()

import django.conf
import django.conf.urls.i18n
import django.conf.urls.static
import django.contrib
import django.contrib.admin
import django.urls

import company.urls
import pages.urls
import tickets.urls
import users.urls


urlpatterns = [
    django.urls.path("", django.urls.include(pages.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("auth/", django.urls.include(users.urls)),
    django.urls.path("company/", django.urls.include(company.urls)),
    django.urls.path("tickets/", django.urls.include(tickets.urls)),
    django.urls.path("i18n/", django.urls.include(django.conf.urls.i18n)),
]

if django.conf.settings.DEBUG:
    import debug_toolbar.toolbar

    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.STATIC_URL,
        document_root=django.conf.settings.STATIC_ROOT,
    )

    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

servicetrack/company/models.py
__all__ = ()

import django.conf
import django.db.models
from django.utils.translation import gettext_lazy as _

import users.models


class Organization(django.db.models.Model):
    name = django.db.models.CharField(
        _("название_организации"),
        max_length=100,
    )

    description = django.db.models.TextField(
        _("описание"),
        blank=True,
        null=True,
    )

    main_manager = django.db.models.OneToOneField(
        django.conf.settings.AUTH_USER_MODEL,
        on_delete=django.db.models.CASCADE,
        related_name="organization",
        verbose_name=_("управляющий_организацией"),
    )

    created_at = django.db.models.DateTimeField(
        _("дата_создания"),
        auto_now_add=True,
    )

    updated_at = django.db.models.DateTimeField(
        _("дата_обновления"),
        auto_now=True,
    )

    class Meta:
        verbose_name = _("организация")
        verbose_name_plural = _("организации")

    def __str__(self):
        return self.name


class WorkerGroup(django.db.models.Model):
    name = django.db.models.CharField(
        _("название_группы"),
        max_length=100,
    )

    description = django.db.models.TextField(
        _("описание"),
        blank=True,
        null=True,
    )

    workers = django.db.models.ManyToManyField(
        django.conf.settings.AUTH_USER_MODEL,
        verbose_name=_("работники"),
        related_name="work_groups",
        blank=True,
        limit_choices_to=django.db.models.Q(
            profile__role=users.models.Profile.Role.WORKER,
        )
        | django.db.models.Q(
            profile__role=users.models.Profile.Role.GROUP_MANAGER,
        ),
    )

    manager = django.db.models.ForeignKey(
        django.conf.settings.AUTH_USER_MODEL,
        verbose_name=_("руководитель_группы"),
        related_name="managed_groups",
        on_delete=django.db.models.SET_NULL,
        null=True,
        blank=True,
        limit_choices_to={
            "profile__role": users.models.Profile.Role.GROUP_MANAGER,
        },
    )

    organization = django.db.models.ForeignKey(
        Organization,
        on_delete=django.db.models.CASCADE,
        related_name="groups",
        verbose_name=_("организация"),
    )

    created_at = django.db.models.DateTimeField(
        _("дата_создания"),
        auto_now_add=True,
    )

    updated_at = django.db.models.DateTimeField(
        _("дата_обновления"),
        auto_now=True,
    )

    class Meta:
        verbose_name = _("рабочая_группа")
        verbose_name_plural = _("рабочие_группы")

    def __str__(self):
        return self.name

servicetrack/company/forms.py
__all__ = ()

import django.contrib.auth
import django.db.models
import django.forms

import company.models
import users.models


class WorkerGroupForm(django.forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

        if self.request:
            organization = self.request.user.profile.organization
            user_model = django.contrib.auth.get_user_model()

            self.fields["manager"].queryset = user_model.objects.filter(
                profile__organization=organization,
                profile__role=users.models.Profile.Role.GROUP_MANAGER,
            )

            self.fields["workers"].queryset = user_model.objects.filter(
                profile__organization=organization,
            ).filter(
                django.db.models.Q(
                    profile__role=users.models.Profile.Role.WORKER,
                )
                | django.db.models.Q(
                    profile__role=users.models.Profile.Role.GROUP_MANAGER,
                ),
            )

            self.fields["workers"].widget = (
                django.forms.CheckboxSelectMultiple()
            )

    def clean_workers(self):
        workers_queryset = self.cleaned_data.get("workers")
        manager = self.cleaned_data.get("manager")

        if workers_queryset and manager and manager in workers_queryset:
            workers_list = list(workers_queryset)
            workers_list.remove(manager)
            return workers_list

        return workers_queryset


class OrganizationForm(django.forms.ModelForm):
    class Meta:
        model = company.models.Organization
        fields = (
            model.name.field.name,
            model.description.field.name,
        )


class WorkerGroupEditForm(WorkerGroupForm):
    class Meta:
        model = company.models.WorkerGroup
        fields = (
            model.name.field.name,
            model.description.field.name,
            model.manager.field.name,
            model.workers.field.name,
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if not self.request.user.profile.is_director:
            self.fields["manager"].disabled = True


class WorkerGroupCreationForm(WorkerGroupForm):
    class Meta:
        model = company.models.WorkerGroup
        fields = (
            model.name.field.name,
            model.description.field.name,
            model.manager.field.name,
            model.workers.field.name,
        )

servicetrack/company/views.py
__all__ = ()

import django.contrib.auth.mixins
import django.db.models
import django.urls
import django.views.generic

import company.forms
import company.models
import core.mixins


class OrganizationView(
    core.mixins.ForbiddenMixin,
    django.views.generic.DetailView,
):
    model = company.models.Organization
    template_name = "company/organization_detail.html"
    context_object_name = "organization"

    def test_func(self):
        organization = self.get_object()
        user_org_id = self.request.user.profile.organization_id
        return user_org_id == organization.pk

    def get_queryset(self):
        return super().get_queryset().select_related("main_manager")

    def get_object(self, queryset=None):
        if not hasattr(self, "object") or self.object is None:
            self.object = super().get_object(queryset)

        return self.object


class OrganizationEditView(
    core.mixins.ForbiddenMixin,
    django.views.generic.UpdateView,
):
    model = company.models.Organization
    form_class = company.forms.OrganizationForm
    template_name = "company/organization_edit.html"
    context_object_name = "organization"

    def test_func(self):
        organization = self.get_object()
        user = self.request.user

        return (
            user.profile.organization == organization
            and user.profile.is_director
        )

    def get_success_url(self):
        return self.request.path


class GroupListView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.ListView,
):
    model = company.models.WorkerGroup
    template_name = "company/group_list.html"
    context_object_name = "groups"

    def get_queryset(self):
        return (
            company.models.WorkerGroup.objects.filter(
                organization_id=self.request.user.profile.organization_id,
            )
            .select_related(
                "manager",
            )
            .annotate(
                workers_count=django.db.models.Count("workers"),
                org_name=django.db.models.F("organization__name"),
            )
        )


class GroupDetailView(
    core.mixins.ForbiddenMixin,
    django.views.generic.DetailView,
):
    model = company.models.WorkerGroup
    template_name = "company/group_detail.html"
    context_object_name = "group"

    def test_func(self):
        group = self.get_object()
        user_org_id = self.request.user.profile.organization_id
        return user_org_id == group.organization.pk

    def get_queryset(self):
        return (
            company.models.WorkerGroup.objects.filter(
                organization_id=self.request.user.profile.organization_id,
            )
            .select_related(
                "manager",
                "organization",
            )
            .prefetch_related(
                "workers",
            )
        )

    def get_object(self, queryset=None):
        if not hasattr(self, "object") or self.object is None:
            self.object = super().get_object(queryset)

        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        group = self.get_object()
        user = self.request.user

        can_edit = user.profile.is_director or group.manager == user

        context["can_edit_group"] = can_edit
        return context


class GroupEditView(
    core.mixins.ForbiddenMixin,
    django.views.generic.UpdateView,
):
    model = company.models.WorkerGroup
    form_class = company.forms.WorkerGroupEditForm
    template_name = "company/group_edit.html"
    context_object_name = "group"

    def test_func(self):
        group = self.get_object()
        user = self.request.user

        if user.profile.organization.pk != group.organization.pk:
            return False

        is_group_manager = (
            user.profile.is_manager and group.manager.pk == user.pk
        )

        return user.profile.is_director or is_group_manager

    def get_success_url(self):
        return django.urls.reverse(
            "company:group_detail",
            kwargs={"pk": self.object.pk},
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class GroupCreateView(
    core.mixins.ForbiddenMixin,
    django.views.generic.CreateView,
):
    model = company.models.WorkerGroup
    form_class = company.forms.WorkerGroupCreationForm
    template_name = "company/group_create.html"
    success_url = django.urls.reverse_lazy("company:group_list")

    def test_func(self):
        return self.request.user.profile.is_director

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        form.instance.organization = self.request.user.profile.organization
        return super().form_valid(form)

servicetrack/templates/company/group_create.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Создание_группы" %} - ServiceTrack{% endblock %}

{% block content %}

<div class="row justify-content-center fade-in">
    <div class="col-md-8 col-lg-6">
        <div class="content-container p-4 p-md-5">

            <h2 class="text-center mb-4">
                {% trans "Создание_группы" %}
            </h2>

            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}

                <div class="mb-3">
                    <label for="{{ form.name.id_for_label }}" class="form-label">
                        {% trans "Название_группы" %}
                    </label>
                    <input type="text"
                           name="{{ form.name.name }}"
                           id="{{ form.name.id_for_label }}"
                           class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                           value="{{ form.name.value|default:'' }}"
                           placeholder="{% trans "Введите_название_группы" %}"
                           required>
                    {% for error in form.name.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="mb-3">
                    <label for="{{ form.description.id_for_label }}" class="form-label">
                        {% trans "Описание" %}
                    </label>
                    <textarea name="{{ form.description.name }}"
                              id="{{ form.description.id_for_label }}"
                              class="form-control {% if form.description.errors %}is-invalid{% endif %}"
                              rows="3"
                              placeholder="{% trans "Описание_группы_(необязательно)" %}">{{ form.description.value|default:'' }}</textarea>
                    {% for error in form.description.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="mb-3">
                    <label for="{{ form.manager.id_for_label }}" class="form-label">
                        {% trans "Руководитель_группы" %}
                    </label>
                    <select name="{{ form.manager.name }}"
                            id="{{ form.manager.id_for_label }}"
                            class="form-select {% if form.manager.errors %}is-invalid{% endif %}">

                        <option value="">— {% trans "Не_назначен" %} —</option>
                        {% for manager in form.manager.field.queryset %}
                            <option value="{{ manager.pk }}" selected>
                                {{ manager.get_full_name|default:manager.username }}
                            </option>
                        {% endfor %}
                    </select>
                    {% for error in form.manager.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="mb-4">
                    <label class="form-label">
                        {% trans "Работники_группы" %}
                    </label>
                    
                    <div class="border rounded p-3">
                        {% if form.workers.field.queryset %}
                            {% for worker in form.workers.field.queryset %}
                                <div class="form-check">
                                    <input class="form-check-input"
                                           type="checkbox"
                                           name="{{ form.workers.name }}"
                                           id="worker_{{ worker.pk }}"
                                           value="{{ worker.pk }}"
                                           {% if worker in form.instance.workers.all %}checked{% endif %}>
                                    <label class="form-check-label" for="worker_{{ worker.pk }}">
                                        {{ worker.get_full_name|default:worker.username }}
                                    </label>
                                </div>
                            {% endfor %}
                        {% else %}
                            <span class="text-muted">{% trans "Нет_доступных_работников" %}</span>
                        {% endif %}
                    </div>

                    {% for error in form.workers.errors %}
                        <div class="text-danger small mt-1">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-lg">
                        
                        {% trans "Создать_группу" %}
                    </button>

                    <a href="{% url 'company:group_list' %}"
                       class="btn btn-secondary">
                        {% trans "Назад_к_списку" %}
                    </a>
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}

servicetrack/templates/company/group_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Группа" %} – ServiceTrack{% endblock %}

{% block content %}

<h2 class="text-center mb-4">
    
    {{ group.name }}
</h2>

<div class="mb-4">
    <h5 class="mb-2">
        {% trans "Информация" %}
    </h5>

    <p class="mb-1">
        <strong>{% trans "Описание" %}:</strong><br>
        {% if group.description %}
            {{ group.description }}
        {% else %}
            <span class="text-muted">{% trans "Описание_не_указано" %}</span>
        {% endif %}
    </p>

    <p class="mb-0 mt-2">
        <strong>{% trans "Организация" %}:</strong>
        {{ group.organization.name }}
    </p>
</div>

<hr>

<div class="mb-4">
    <h5 class="mb-2">
        {% trans "Руководитель_группы" %}
    </h5>
    {% if group.manager %}
        <p class="mb-0">
            {{ group.manager.get_full_name|default:group.manager.username }}<br>
            <span class="text-muted">@{{ group.manager.username }}</span>
        </p>
    {% else %}
        <p class="text-muted mb-0">{% trans "Руководитель_не_назначен" %}</p>
    {% endif %}
</div>

<hr>

<div class="mb-4">
    <h5 class="mb-3">
        {% trans "Работники_группы" %}
    </h5>

    {% if group.workers.all|length %}
        <ul class="list-group">
            {% for worker in group.workers.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <strong>
                            {{ worker.get_full_name|default:worker.username }}
                        </strong>
                        <div class="text-muted small">@{{ worker.username }}</div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-muted">{% trans "В_группе_пока_нет_работников" %}</p>
    {% endif %}
</div>

<hr>

<div class="row mb-4">
    <div class="col-md-6">
        <small class="text-muted">
            
            {% trans "Создана" %}: {{ group.created_at|date:"d.m.Y H:i" }}
        </small>
    </div>
    <div class="col-md-6 text-md-end">
        <small class="text-muted">
            
            {% if group.created_at == group.updated_at %}
                {% trans "Не_изменялась" %}
            {% else %}
                {% trans "Обновлена" %}: {{ group.updated_at|date:"d.m.Y H:i" }}
            {% endif %}
        </small>
    </div>
</div>
{% if can_edit_group %}
<div class="d-flex justify-content-end gap-2">
    <a href="{% url 'company:group_edit' group.pk %}"
       class="btn btn-outline-primary">
        
        {% trans "Редактировать" %}
    </a>
</div>
{% endif %}

{% endblock %}

servicetrack/templates/company/group_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Группы" %} - ServiceTrack{% endblock %}

{% block content %}
<div class="tickets-container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h1 class="mb-1">{% trans "Рабочие_группы" %}</h1>
            <p class="text-muted mb-0">
                {{ user.profile.organization_name }}
            </p>
        </div>

        {% if user.profile.is_director %}
            <a href="{% url 'company:group_create' %}" class="btn btn-primary">
                {% trans "Создать_группу" %}
            </a>
        {% endif %}
    </div>

    <div class="card-body p-0">
        {% if groups %}
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead class="table-light">
                        <tr>
                            <th>#</th>
                            <th>{% trans "Название" %}</th>
                            <th>{% trans "Руководитель" %}</th>
                            <th>{% trans "Количество_работников" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for group in groups %}
                            <tr onclick="window.location='{% url 'company:group_detail' group.pk %}'" style="cursor: pointer;">
                                <td>{{ forloop.counter }}</td>
                                <td class="fw-semibold">{{ group.name }}</td>
                                <td>
                                    {% if group.manager %}
                                        {{ group.manager.username }}
                                    {% else %}
                                        <span class="text-muted">{% trans "Не_назначен" %}</span>
                                    {% endif %}
                                </td>
                                <td>
                                    {{ group.workers_count }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <div class="text-center py-5">
                
                <h4 class="text-muted mt-3">{% trans "Групп_пока_нет" %}</h4>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

servicetrack/templates/company/organization_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Организация" %} - ServiceTrack{% endblock %}

{% block content %}

<h2 class="text-center mb-4">
    
    {{ organization.name }}
</h2>

<div class="mb-4">
    <h5 class="mb-2">
        {% trans "Информация" %}
    </h5>

    <p class="mb-1">
        <strong>{% trans "Описание" %}:</strong><br>
        {% if organization.description %}
            {{ organization.description }}
        {% else %}
            <span class="text-muted">{% trans "Описание_не_указано" %}</span>
        {% endif %}
    </p>
</div>

<hr>

<div class="mb-4">
    <h5 class="mb-2">
        {% trans "Руководитель_организации" %}
    </h5>

    <p class="mb-0">
        {{ organization.main_manager.get_full_name|default:organization.main_manager.username }}
        <br>
        <span class="text-muted">@{{ organization.main_manager.username }}</span>
    </p>
</div>

<hr>

<div class="row mb-4">
    <div class="col-md-6">
        <small class="text-muted">
            
            {% trans "Создана" %}: {{ organization.created_at|date:"d.m.Y H:i" }}
        </small>
    </div>
    <div class="col-md-6 text-md-end">
        <small class="text-muted">
            
            {% if organization.created_at == organization.updated_at %}
                {% trans "Не_изменялась" %}
            {% else %}
                {% trans "Обновлена" %}: {{ organization.updated_at|date:"d.m.Y H:i" }}
            {% endif %}
        </small>
    </div>
</div>

{% if user.profile.is_director %}
<div class="d-flex justify-content-end gap-2">
    <a href="{% url 'company:organization_edit' organization.pk %}"
        class="btn btn-outline-primary">
        
        {% trans "Редактировать" %}
    </a>
</div>
{% endif %}

{% endblock %}

servicetrack/templates/company/organization_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Организация" %} - ServiceTrack{% endblock %}

{% block content %}
<div class="row justify-content-center fade-in">
    <div class="col-md-10 col-lg-7">
        <div class="content-container p-4 p-md-5">

            <h2 class="text-center mb-4">
                
                {% trans "Редактирование_организации" %}
            </h2>

            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}

                <div class="mb-3">
                    <label for="{{ form.name.id_for_label }}" class="form-label">
                        {% trans "Название_организации" %}
                    </label>
                    <input type="text"
                           name="{{ form.name.name }}"
                           id="{{ form.name.id_for_label }}"
                           class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                           value="{{ form.name.value|default:'' }}"
                           placeholder="{% trans "Введите_название_организации" %}"
                           required>
                    {% for error in form.name.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="mb-4">
                    <label for="{{ form.description.id_for_label }}" class="form-label">
                        {% trans "Описание" %}
                    </label>
                    <textarea name="{{ form.description.name }}"
                              id="{{ form.description.id_for_label }}"
                              rows="4"
                              class="form-control {% if form.description.errors %}is-invalid{% endif %}"
                              placeholder="{% trans "Краткое_описание_организации" %}">{{ form.description.value|default:'' }}</textarea>
                    {% for error in form.description.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="d-flex justify-content-between">
                    <a href="{% url 'company:organization_detail' organization.pk %}"
                       class="btn btn-outline-secondary">
                        
                        {% trans "Назад" %}
                    </a>

                    <button type="submit" class="btn btn-primary">
                        
                        {% trans "Сохранить_изменения" %}
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}